# Introduction SciPy

SciPy, pronounced as Sigh Pi, is a scientific python open source, distributed under the BSD licensed library to perform Mathematical, Scientific and Engineering Computations.

The SciPy library depends on NumPy, which provides convenient and fast N-dimensional array manipulation. The SciPy library is built to work with NumPy arrays and provides many user-friendly and efficient numerical practices such as routines for numerical integration and optimization. Together, they run on all popular operating systems, are quick to install and are free of charge. NumPy and SciPy are easy to use, but powerful enough to depend on by some of the world's leading scientists and engineers.

## Data Structure

The basic data structure used by SciPy is a multidimensional array provided by the NumPy module. NumPy provides some functions for Linear Algebra, Fourier Transforms and Random Number Generation, but not with the generality of the equivalent functions in SciPy.

## Setup

Standard Python distribution does not come bundled with any SciPy module. To install SciPy we can use either **Anaconda Navigator** or Python package manager.

## Basic Functionality

By default, all the NumPy functions have been available through the SciPy namespace. There is no need to import the NumPy functions explicitly, when SciPy is imported. The main object of NumPy is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy, dimensions are called as axes. The number of axes is called as rank.

As SciPy is built on top of NumPy arrays, understanding of NumPy basics is necessary. As most parts of linear algebra deals with matrices only.

## NumPy Vector

A Vector can be created in multiple ways. Some of them are described below.

### Converting Python array-like objects to NumPy

Let us consider the following example.

In [2]:
import numpy as np
list = [1,2,3,4]
arr = np.array(list)
print(arr)

[1 2 3 4]


## Intrinsic NumPy Array Creation

NumPy has built-in functions for creating arrays from scratch. Some of these functions are explained below.

### Using `zeros()`

The zeros(shape) function will create an array filled with 0 values with the specified shape. The default dtype is float64. Let us consider the following example.

In [4]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


### Using `ones()`

The ones(shape) function will create an array filled with 1 values. It is identical to zeros in all the other respects. Let us consider the following example.

In [5]:
print(np.ones((2, 3)))

[[1. 1. 1.]
 [1. 1. 1.]]


### Using `arange()`

The `arange()` function will create arrays with regularly incrementing values. Let us consider the following example.

In [6]:
print(np.arange(7))

[0 1 2 3 4 5 6]


### Defining the data type of the values

Let us consider the following example.

In [8]:
arr = np.arange(2, 10, dtype = float)
print(arr)
print("Array Data Type :",arr.dtype)

[2. 3. 4. 5. 6. 7. 8. 9.]
Array Data Type : float64


### Using `linspace()`

The `linspace()` function will create arrays with a specified number of elements, which will be spaced equally between the specified beginning and end values. Let us consider the following example.

In [10]:
print(np.linspace(1., 4., 6))

[1.  1.6 2.2 2.8 3.4 4. ]


## Matrix

A matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as * (matrix multiplication) and ** (matrix power). Let us consider the following example.

In [11]:
print(np.matrix('1 2; 3 4'))

[[1 2]
 [3 4]]


### Conjugate Transpose of Matrix

This feature returns the (complex) conjugate transpose of self. Let us consider the following example.

In [18]:
mat = np.matrix('1 2; 3 4')
print("Original: \n", mat)
print("Conjugate: \n", mat.H)

Original: 
 [[1 2]
 [3 4]]
Conjugate: 
 [[1 3]
 [2 4]]


### Transpose of Matrix

This feature returns the transpose of self. Let us consider the following example.

In [16]:
mat = np.matrix('1 2; 3 4')
print("Original: \n", mat)
print("Transpose: \n", mat.T)

Original: 
 [[1 2]
 [3 4]]
Transpose: 
 [[1 3]
 [2 4]]


When we transpose a matrix, we make a new matrix whose rows are the columns of the original. A conjugate transposition, on the other hand, interchanges the row and the column index for each matrix element. The inverse of a matrix is a matrix that, if multiplied with the original matrix, results in an identity matrix.

## SciPy Constants Package

The `scipy.constants` package provides various constants. We have to import the required constant and use them as per the requirement. Let us see how these constant variables are imported and used.

To start with, let us compare the ‘pi’ value by considering the following example.

In [31]:
import scipy.constants
import math

print("sciPy - pi = %.16f" % scipy.constants.pi)
print("math - pi = %.16f" % math.pi)

sciPy - pi = 3.1415926535897931
math - pi = 3.1415926535897931


## List of Constants Available

Please refer to [Scipy official API reference](https://docs.scipy.org/doc/scipy/reference/constants.html) for list available constants. 

Remembering all of these are a bit tough. The easy way to get which key is for which function is with the `scipy.constants.find()` method. Let us consider the following example.

In [32]:
import scipy.constants

res = scipy.constants.physical_constants["characteristic impedance of vacuum"]
print(res)

(376.730313668, 'ohm', 5.7e-08)


## FFTpack

Fourier Transformation is computed on a time domain signal to check its behavior in the frequency domain. Fourier transformation finds its application in disciplines such as signal and noise processing, image processing, audio signal processing, etc. SciPy offers the fftpack module, which lets the user compute fast Fourier transforms.

## Fast Fourier Transform

Let us understand what fast Fourier transform is in detail.

### One Dimensional Discrete Fourier Transform

The FFT $y[k]$ of length $N$ of the length-N sequence $x[n]$ is calculated by `fft()` and the inverse transform is calculated using `ifft()`. Let us consider the following example

In [33]:
#Importing the fft and inverse fft functions from fftpackage
from scipy.fftpack import fft

#create an array with random n numbers
x = np.array([1.0, 2.0, 1.0, -1.0, 1.5])

#Applying the fft function
y = fft(x)
print(y)

[ 4.5       -0.j          2.08155948-1.65109876j -1.83155948+1.60822041j
 -1.83155948-1.60822041j  2.08155948+1.65109876j]


In [35]:
from scipy.fftpack import ifft

yinv = ifft(y)
print(yinv)

[ 1. +0.j  2. +0.j  1. +0.j -1. +0.j  1.5+0.j]


The `scipy.fftpack` module allows computing fast Fourier transforms. As an illustration, a (noisy) input signal may look as follows:

In [36]:
time_step = 0.02
period = 5.
time_vec = np.arange(0, 20, time_step)
sig = np.sin(2 * np.pi / period * time_vec) + 0.5 *np.random.randn(time_vec.size)
print(sig.size)

1000


We are creating a signal with a time step of $0.02$ seconds. The last statement prints the size of the signal `sig`. 

We do not know the signal frequency; we only know the sampling time step of the signal `sig`. The signal is supposed to come from a real function, so the Fourier transform will be symmetric. The `scipy.fftpack.fftfreq()` function will generate the sampling frequencies and scipy.`fftpack.fft()` will compute the fast Fourier transform.

In [37]:
from scipy import fftpack
sample_freq = fftpack.fftfreq(sig.size, d = time_step)
sig_fft = fftpack.fft(sig)
print(sig_fft)

[  2.57005411-0.00000000e+00j   9.92388118+7.13994578e+00j
   2.59787987-1.32477556e+01j -18.56270574-5.10604697e+00j
 -14.73178441-5.02151502e+02j  -8.57042913+6.32345621e+00j
 -19.92937949+1.44569248e+01j  -1.13310941+5.43181276e+00j
  12.02694849-6.61519854e+00j  -2.0100638 -2.39807394e+00j
  -3.27546398+1.85645344e+00j  -6.41581509-3.12241896e+00j
  -8.70595781-1.83493311e+01j   3.75062648-6.49925467e+00j
  12.90001216+2.32954442e+00j  15.51648125-4.47000142e-01j
  -0.40900842+2.28508189e+01j   3.48467715-9.70218641e+00j
 -13.55888252+5.89325150e+00j   2.33878603-9.98512056e+00j
  11.13811386-6.78943258e+00j   2.47010783+1.69536189e+00j
   4.07020461+2.53682287e+00j  29.62590666+4.99362564e+00j
   1.76505165+7.10178986e+00j   6.19397731+8.84088644e+00j
  -2.48221933-3.73817124e+00j  14.21564019+1.83893460e+01j
 -12.17136387-3.43321071e+00j   6.62469254+6.75608184e+00j
  10.61907378+8.28364690e+00j  27.57195262-1.95299691e+01j
  11.97298688-6.51106831e+00j   1.79202001-6.74677361e-0

### Discrete Cosine Transform

A Discrete Cosine Transform (DCT) expresses a finite sequence of data points in terms of a sum of cosine functions oscillating at different frequencies. SciPy provides a DCT with the function dct and a corresponding IDCT with the function idct. Let us consider the following example.

In [4]:
import numpy as np
from scipy.fftpack import dct

print(dct(np.array([4., 3., 5., 10., 5., 3.])))

[ 60.          -3.48476592 -13.85640646  11.3137085    6.
  -6.31319305]


The inverse discrete cosine transform reconstructs a sequence from its discrete cosine transform (DCT) coefficients. The `idct` function is the inverse of the `dct` function. Let us understand this with the following example.

In [6]:
from scipy.fftpack import idct
print(idct(np.array([4., 3., 5., 10., 5., 3.])))

[ 39.15085889 -20.14213562  -6.45392043   7.13341236   8.14213562
  -3.83035081]
