# Introduction to NumPy

## What is NumPy? 
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays. It is the fundamental package for scientific computing with Python. It is open-source software.

## Features of NumPy
NumPy has various features including these important ones:
* A powerful N-dimensional array object
* Sophisticated (broadcasting) functions
* Tools for integrating C/C++ and Fortran code
* Useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy in Python can also be used as an efficient multi-dimensional container of generic data. Arbitrary data types can be defined using Numpy which allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

## Install Python NumPy

Numpy can be installed for Mac and Linux users in a number of ways:

1. Using `conda` package manager: `conda install numpy`
2. Anaconda Navigator
3. Using `pip` command: `pip install numpy`

## Arrays in NumPy
NumPy's main object is the homogeneous multidimensional array.

* It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
* In NumPy, dimensions are called axes. The number of axes is rank.
* NumPy's array class is called `ndarray`. It is also known by the alias **array**.

### Example
In the following example, we are creating a two-dimensional array that has the **rank** of 2 as it has 2 **axes**. The first axis(dimension) is of length 2, i.e., the number of rows, and the second axis(dimension) is of length 3, i.e., the number of columns. The overall shape of the array can be represented as (2, 3)

In [4]:
import numpy as np 

# Create array object 
arr = np.array( [[ 1, 2, 3], 
				[ 4, 2, 5]] ) 

print("Array:\n", arr)

Array:
 [[1 2 3]
 [4 2 5]]


Print the type of `arr` object 

In [4]:

print("Array is of type: ", type(arr)) 

Array is of type:  <class 'numpy.ndarray'>


Print array dimensions (axes) 


In [2]:
print("No. of dimensions: ", arr.ndim) 

No. of dimensions:  2


Print shape of array 


In [3]:
print("Shape of array: ", arr.shape) 

Shape of array:  (2, 3)


Print size (total number of elements) of array 


In [5]:
print("Size of array: ", arr.size) 

Size of array:  6



Print the type of elements in array 


In [6]:
print("Array stores elements of type: ", arr.dtype)

Array stores elements of type:  int64


## NumPy Array Creation

There are various ways of Numpy array creation in Python. They are as follows:

### Array from list of tuple
You can create an array from a regular Python list or tuple using the `array()` function. The type of the resulting array is deduced from the type of the elements in the sequences. Let’s see this implementation:

In [7]:
import numpy as np 

# Creating array from list with type float 
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float') 
print ("Array created using passed list:\n", a) 

# Creating array from tuple 
b = np.array((1 , 3, 2)) 
print ("\nArray created using passed tuple:\n", b)


Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]


In [8]:
print("Array a shape:\n", a.shape)

Array a shape:
 (2, 3)


In [9]:
print("Array b shape:\n", b.shape)

Array b shape:
 (3,)


### Array from content placeholder
Often, the element is of an array is originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with **initial placeholder content**. These minimize the necessity of growing arrays, an expensive operation. For example: `np.zeros`, `np.ones`, `np.full`, `np.empty`, etc.

To create sequences of numbers, NumPy provides a function analogous to the range that returns arrays instead of lists.

In [20]:
# Creating a 3x4 array with all zeros 
c = np.zeros((35, 68)) 
print("An array initialised with all zeros:\n", c) 

# Create a constant value array of complex type 
d = np.full((3, 3), 6, dtype = 'complex') 
print ("An array initialized with all 6s. Array type is complex:\n", d) 

# Create an array with random values 
e = np.random.random((2, 2)) 
print("A random array:\n", e)


An array initialised with all zeros:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]
A random array:
 [[0.65795978 0.59688555]
 [0.99386084 0.11813309]]


In [21]:
print("Array c shape:\n", c.shape)

Array c shape:
 (35, 68)


### Array from `arange` Function
This function returns evenly spaced values within a given interval. Step size is specified.

In [22]:
# Create a sequence of integers 
# from 0 to 30 with steps of 5 
f = np.arange(0, 30, 5)
print ("A sequential array with steps of 5:\n", f)


A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


### Array from `linspace`
It returns evenly spaced values within a given interval.

In [24]:
# Create a sequence of 30 values in range 0 to 5 
g = np.linspace(0, 5, 30) 
print ("A sequential array with 10 values between 0 and 5:\n", g)

A sequential array with 10 values between 0 and 5:
 [0.         0.17241379 0.34482759 0.51724138 0.68965517 0.86206897
 1.03448276 1.20689655 1.37931034 1.55172414 1.72413793 1.89655172
 2.06896552 2.24137931 2.4137931  2.5862069  2.75862069 2.93103448
 3.10344828 3.27586207 3.44827586 3.62068966 3.79310345 3.96551724
 4.13793103 4.31034483 4.48275862 4.65517241 4.82758621 5.        ]


### Reshaping Array
We can use reshape method to reshape an array. Consider an array with shape (a1, a2, a3, ... , aN). We can reshape and convert it into another array with shape (b1, b2, b3, ... , bM). The only required condition is a1 x a2 x a3 x ... x aN = b1 x b2 x b3 x ... x bM. (i.e. the original size of the array remains unchanged.)

In [25]:
# Reshaping 3x4 array to 2x2x3 array 
arr = np.array([[1, 2, 3, 4], 
				[5, 2, 4, 2], 
				[1, 2, 0, 1]]) 

newarr = arr.reshape(2, 2, 3) 

print ("Original array:\n", arr) 
print("---------------") 
print ("Reshaped array:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
---------------
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


### Flatten Array
We can use flatten method to get a copy of the array collapsed into one dimension. It accepts order argument.

In [27]:
# Flatten array 
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
flat_arr = arr.flatten() 

print ("Original array:\n", arr) 
print ("Flattened array:\n", flat_arr)


Original array:
 [[1 2 3]
 [4 5 6]]
Flattened array:
 [1 2 3 4 5 6]


## NumPy Array Indexing
Knowing the basics of NumPy array indexing is important for analyzing and manipulating the array object. NumPy in Python offers many ways to do array indexing.

1. **Slicing**: Just like lists in Python, NumPy arrays can be sliced. As arrays can be multidimensional, you need to specify a slice for each dimension of the array.
2. **Integer array indexing**: In this method, lists are passed for indexing for each dimension. One-to-one mapping of corresponding elements is done to construct a new arbitrary array.
3. **Boolean array indexing**: This method is used when we want to pick elements from the array which satisfy some condition.

### Example
The following demonstrates NumPy indexing

In [32]:
# A random 4x4 array 
arr = np.array([[-1, 2, 0, 4], 
				[4, -0.5, 6, 0], 
				[2.6, 0, 7, 8], 
				[3, -7, 4, 2.0]]) 

# Slicing array 
print("Original array:\n", arr)
temp = arr[:2, ::2] 
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp) 

# Integer array indexing example
print("\nOriginal array:\n", arr)
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]] 
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp) 

# boolean array indexing example 
cond = arr > 0 # cond is a boolean array
print("\nBoolean flags\n",cond)
temp = arr[cond] 
print ("\nElements greater than 0:\n", temp) 


Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Original array:
 [[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Boolean flags
 [[False  True False  True]
 [ True False  True False]
 [ True False  True  True]
 [ True False  True  True]]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


## NumPy Basic Operations
The are many built-in arithmetic functions is provided in Python NumPy.

### Operations on a single NumPy array
We can use overloaded arithmetic operators to do element-wise operations on the array to create a new array. In the case of `+=`, `-=`, `*=` operators, the existing array is modified.

### Example
The following demonstrates basic operations on single array 


In [33]:
# Create an 1D array
a = np.array([1, 2, 5, 3]) 

# add 1 to every element 
print ("Adding 1 to every element:", a+1) 

# subtract 3 from each element 
print ("Subtracting 3 from each element:", a-3) 

# multiply each element by 10 
print ("Multiplying each element by 10:", a*10) 

# square each element 
print ("Squaring each element:", a**2) 

# modify existing array 
a *= 2
print ("Doubled each element of original array:", a) 

# transpose of array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]]) 

print ("\nOriginal array:\n", a) 
print ("Transpose of array:\n", a.T)


Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


## NumPy – Unary Operators

Many unary operations are provided as a method of `ndarray` class. This includes `sum`, `min`, `max`, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.

### Example
The following shows the use of unary operators in NumPy

In [36]:
# Create an array
arr = np.array([[1, 5, 6], 
				[4, 7, 2], 
				[3, 1, 9]]) 

# maximum element of array 
print ("Largest element is:", arr.max()) 
print ("Row-wise maximum elements:", arr.max(axis = 1)) 

# minimum element of array 
print ("Row-wise minimum elements:", arr.min(axis = 1)) 
print ("Column-wise minimum elements:", arr.min(axis = 0)) 

# sum of array elements 
print ("Sum of all array elements:", arr.sum()) 

# cumulative sum along each row 
print ("Cumulative sum along each row:\n", arr.cumsum(axis = 1))
print ("Cumulative sum along each column :\n", arr.cumsum(axis = 0)) 


Largest element is: 9
Row-wise maximum elements: [6 7 9]
Row-wise minimum elements: [1 2 1]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]
Cumulative sum along each column :
 [[ 1  5  6]
 [ 5 12  8]
 [ 8 13 17]]


## NumPy – Binary Operators

These operations apply to the array elementwise and a new array is created. You can use all basic arithmetic operators like `+`, `-`, `/`,  etc. In the case of `+=`, `-=`, `=` operators, the existing array is modified.

### Example
The following demonstrates binary operators in NumPy 

In [31]:
a = np.array([[1, 2], [3, 4]]) 

b = np.array([[4, 3], [2, 1]]) 

# add arrays 
print ("Array sum:\n", a + b) 

# multiply arrays (elementwise multiplication) 
print ("Array multiplication:\n", a*b) 

# matrix multiplication 
print ("Matrix multiplication:\n", a.dot(b)) 


Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


## Introduction to NumPy’s Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, exp, etc. These functions also operate elementwise on an array, producing an array as output.

*Note: All the operations we did above using overloaded operators can be done using ufuncs like np.add, np.subtract, np.multiply, np.divide, np.sum, etc.* 

### Example
The following demonstrates universal functions in NumPy

In [38]:
# create an array of sine values 
a = np.array([0, np.pi/2, np.pi]) 

print("Array:\n", a)
print ("Sine values of array elements:", np.sin(a)) 

# exponential values 
a = np.array([0, 1, 2, 3]) 
print ("Exponent of array elements:", np.exp(a)) 

# square root of array values 
print ("Square root of array elements:", np.sqrt(a)) 


Array:
 [0.         1.57079633 3.14159265]
Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


## Why is Numpy faster in Python?
NumPy is a Python fundamental package used for efficient manipulations and operations on High-level mathematical functions, Multi-dimensional arrays, Linear algebra, Fourier Transformations, Random Number Capabilities, etc. It provides tools for integrating C, C++, and Fortran code in Python. NumPy is mostly used in Python for scientific computing. 

Below compares NumPy Arrays and Lists in Python in terms of execution time. 

In [39]:
# importing required packages
import time

# size of arrays and lists
size = 1000000

# declaring lists
list1 = range(size)
list2 = range(size)

# declaring arrays
array1 = np.arange(size) 
array2 = np.arange(size)

# list
initialTime = time.time()
resultantList = [(a * b) for a, b in zip(list1, list2)]

# calculating execution time
print("Time taken by Lists :", 
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
resultantArray = array1 * array2

# calculating execution time 
print("Time taken by NumPy Arrays :", (time.time() - initialTime), "seconds")


Time taken by Lists : 0.12648582458496094 seconds
Time taken by NumPy Arrays : 0.005352973937988281 seconds


### NumPy Arrays are faster than Python Lists because of the following reasons

1. An array is a collection of homogeneous data-types that are stored in contiguous memory locations. On the other hand, a list in Python is a collection of heterogeneous data types stored in non-contiguous memory locations.
2. The NumPy package breaks down a task into multiple fragments and then processes all the fragments parallelly.
3. The NumPy package integrates C, C++, and Fortran codes in Python. These programming languages have very little execution time compared to Python.

Below compares the execution time of different operations on NumPy arrays and Python Lists:  

In [40]:
# size of arrays and lists
size = 1000000

# declaring lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

# declaring arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Concatenation
print("\nConcatenation:")

# list
initialTime = time.time()
list1 = list1 + list2

# calculating execution time
print("Time taken by Lists :",
	(time.time() - initialTime),
	"seconds")

# NumPy array
initialTime = time.time()
array = np.concatenate((array1, array2), axis = 0)

# calculating execution time 
print("Time taken by NumPy Arrays :", (time.time() - initialTime), "seconds")


# Dot Product
dot = 0
print("\nDot Product:")

# list
initialTime = time.time()
for a, b in zip(list1, list2): 
    dot = dot + (a * b)
		
# calculating execution time
print("Time taken by Lists :", (time.time() - initialTime), "seconds")

# NumPy array
initialTime = time.time()
array = np.dot(array1, array2)

# calculating execution time 
print("Time taken by NumPy Arrays :", (time.time() - initialTime),"seconds")


# Scalar Addition 
print("\nScalar Addition:")

# list
initialTime = time.time()
list1 =[i + 2 for i in range(size)]

# calculating execution time
print("Time taken by Lists :", (time.time() - initialTime),"seconds")

# NumPy array
initialTime = time.time()
array1 = array1 + 2

# calculating execution time 
print("Time taken by NumPy Arrays :", (time.time() - initialTime), "seconds")


# Deletion
print("\nDeletion: ")

# list
initialTime = time.time()
del(list1)

# calculating execution time
print("Time taken by Lists :",(time.time() - initialTime),"seconds")

# NumPy array
initialTime = time.time()
del(array1)

# calculating execution time 
print("Time taken by NumPy Arrays :", (time.time() - initialTime),"seconds")



Concatenation:
Time taken by Lists : 0.021097898483276367 seconds
Time taken by NumPy Arrays : 0.014459848403930664 seconds

Dot Product:
Time taken by Lists : 0.15607094764709473 seconds
Time taken by NumPy Arrays : 0.004182100296020508 seconds

Scalar Addition:
Time taken by Lists : 0.10200190544128418 seconds
Time taken by NumPy Arrays : 0.0035181045532226562 seconds

Deletion: 
Time taken by Lists : 0.018311023712158203 seconds
Time taken by NumPy Arrays : 0.003509998321533203 seconds
